### ISSUE TITLE
How to cancel AcquireLock()?

### ISSUE THREAD

**Issue by jtackaberry** [cirello-io/dynamolock#106]
I'd like to have my process abort cleanly (and swiftly) upon SIGINT, but `Client.AcquireLock()` blocks for up to the lease time if the lock is already acquired (or it's stale).

At first I thought I could use `FailIfLocked()` and implement my own retry loop, but then I got bit by #44 because the stale lock detection is bypassed in that case.

I don't entirely understand the recommendation in #84, because even with `DisableHeartbeat()` a call to `AcquireLock()` will block until the full lease duration has elapsed.

Then I thought perhaps I could call `Client.Close()` to force the issue, however that merely blocks waiting for the mutex held by `AcquireLock()` to be released.

The right solution would involve a new method like `AcquireLockWithContext()` where I can pass in a context which is checked between each refresh (which in turn calls the `GetContext()` variants of the DynamoDB API, such as `DynamoDB.GetItemWithContext()` rather than `DynamoDB.GetItem()`, and passes in this user-provided context so things don't block untowardly within the AWS SDK either), however I'd be happy with a simple kludge to interrupt `AcquireLock()` even if it meant waiting the refresh period, which is a bit more tolerable than the entire lease timeout.

Any ideas?

Thanks!

**Comment by ucirello** [comment]
Thanks for the report. @jtackaberry could you please test https://github.com/cirello-io/dynamolock/commit/829fa9ac2bb76c0fd56dcbb0349d22de781f7c80 ?

If it works for you, then I am going to make a release.

**Comment by jtackaberry** [comment]
Wow, that was staggeringly quick.  Were you sitting on that? ;)

Will take this out for a spin tonight.  Thanks @ucirello!

**Comment by jtackaberry** [comment]
So far so good, @ucirello.  Previous code compiled and worked fine with the changes, and using the new `AcquireLockWithContext()` method is working as expected.  I have a long running process that maintains a lock, which I can leave running overnight and will report back in a few hours.

I also just submitted a PR to tidy up a couple places where `time.Sleep()` was being called, preventing quicker cancellation.

Thanks!

**Comment by jtackaberry** [comment]
Process has been running for 14 hours.  No problems to report.

**Comment by ucirello** [comment]
https://github.com/cirello-io/dynamolock/releases/tag/v1.4.0 is now available.
