### ISSUE TITLE
support for int64 leaseDuration

### ISSUE THREAD

**Issue by novaturient95** [cirello-io/dynamolock#113]
Hi, can you add support to save `leaseDuration` in int64 (`time.Duration().Milliseconds()`) . This would make it compatible to Java lock client, since it is trying to fetch `leaseDuration` as `AtomicLong` and that is causing `java.lang.NumberFormatException`

**Comment by ucirello** [comment]
Hi @novaturient95, thanks for this issue.

Could you please produce snippets of code both in Java and Go showing the problem?

**Comment by novaturient95** [comment]
Thanks @ucirello for your response.

When persisting leaseDuration to DB in dynamoLock (https://github.com/cirello-io/dynamolock/blob/master/client.go#L604), it is saving duration as string. So lease duration 3s  will be saved as '3s'. But Java client expects it to be a Long and in ms, 
i.e it is expecting something like '3000'.

AmazonDynamoDBLockClient : https://github.com/amazon-archives/dynamodb-lock-client/blob/master/src/main/java/com/amazonaws/services/dynamodbv2/AmazonDynamoDBLockClient.java#L1004

**Comment by ucirello** [comment]
hi @novaturient95 -- I think this change can be done. PRs are always welcome. You are welcome to try and fix it. Keep in mind that you need to make sure it is backward compatible with previous versions. Thanks again for the report.

**Comment by ucirello** [comment]
Please - reopen this issue when you have a PR ready. Thanks
