### ISSUE TITLE
lock.IsExpired() always returns true

### ISSUE THREAD

**Issue by sitilge** [cirello-io/dynamolock#116]
Hi,

I've started using the nice project and maybe I am getting some things wrong, but things are breaking for me. So I am using the Cobra library for building a CLI app and using dynamolock for locking/unlocking a critical section. The workflow then is as follows

````bash
my-command lock //acquire the lock
my-command unlock //release the lock
````
I was following the given example, and the locking part (when I call `my-command lock`) is as follows:

````go
sessionAWS := session.Must(session.NewSession(&aws.Config{
	Region: aws.String("eu-north-1"),
}))

sessionDynamo := dynamodb.New(sessionAWS)

client, err := dynamolock.New(
	sessionDynamo,
	"my-table",
	dynamolock.WithLeaseDuration(10*time.Second),
	dynamolock.WithHeartbeatPeriod(2*time.Second),
	dynamolock.WithOwnerName("abcd"),
)
if err != nil {
	fmt.Println(err)
	os.Exit(1)
}
//Do not close the connection, as we need to keep the
//item locked. Close after successful unlocking.
//defer client.Close()

lock, err := client.AcquireLock(
	"my-key",
	dynamolock.FailIfLocked(),
)
if err != nil {
	fmt.Println(err)
	os.Exit(1)
}

fmt.Printf("%s acquired the lock\n", lock.OwnerName())
````
And then, when I call `my-command unlock` I want the lock to be released. The unlock part is as follows:

````go
sessionAWS := session.Must(session.NewSession(&aws.Config{
	Region: aws.String("eu-north-1"),
}))

sessionDynamo := dynamodb.New(sessionAWS)

client, err := dynamolock.New(
	sessionDynamo,
	"my-table",
	dynamolock.WithLeaseDuration(10*time.Second),
	dynamolock.WithHeartbeatPeriod(2*time.Second),
	dynamolock.WithOwnerName("abcd"),
)
if err != nil {
	fmt.Println(err)
	os.Exit(1)
}

lock, err := client.Get("my-key")
if err != nil {
	fmt.Println(err)
	os.Exit(1)
}

if lock.IsExpired() {
	fmt.Println("lock is expired")
	os.Exit(1)
}

ok, err := client.ReleaseLock(lock)
if err != nil {
	fmt.Println(err)
	os.Exit(1)
}

if !ok {
	fmt.Println("lost lock before releasing")
	os.Exit(1)
}

err = client.Close()
if err != nil {
	fmt.Println(err)
	os.Exit(1)
}

fmt.Printf("%s released the lock\n", lock.OwnerName())
````
The `lock.isExpired` is always true. I was thinking that maybe it happens because the client gets created each time new, and the new client does not own the lock, and ultimately the `isExpired` returns true. If so, do you have an idea to solve it?

What am I missing here?

Thank you

**Comment by ucirello** [comment]
Hi @sitilge - Thanks for you message.

> The lock.isExpired is always true. I was thinking that maybe it happens because the client gets created each time new, and the new client does not own the lock, and ultimately the isExpired returns true. 

I would say your understanding is correct and you are not missing anything here.

I believe the solution to your problem is to hold the lock while you execute the underlying commands. Like: https://github.com/cirello-io/dynamolock/blob/master/_examples/cmd/lock/main.go

**Comment by sitilge** [comment]
Hi,

A bit tangential, but I found a solution - having a simple background process, e.g. a process listening to port, does the job incredibly well. Then the CLI can be used as a frontend and call the process actually responsible for locking.
