### ISSUE TITLE
ResourceNotFoundException while attempting to create a new table

### ISSUE THREAD

**Issue by finferflu** [cirello-io/dynamolock#120]
I've used the sample code in the README file, and while running for the first time, I can see this error:

```
2020/11/09 19:06:16 ensuring table exists
2020/11/09 19:06:16 ResourceNotFoundException: Requested resource not found
exit status 1
```

By looking at the AWS Console, I can see that the DynamoDB table is still being created when that error comes up and a subsequent run is successful. I haven't looked into the code, however, I think we need the `CreateTable` to wait until the create operation is complete before exiting.

**Comment by ucirello** [comment]
Hi @finferflu - thanks for this report. I am hazy with the idea of making create table waiting on creation, at the same time, it would be better to make the documentation less frustrating. I am going to think of something and try and fix this situation somehow.

**Comment by ucirello** [comment]
Hi @finferflu -- see if https://github.com/cirello-io/dynamolock/commit/ed2a3ee772b7f1ef6c9cf5c0c284f04d5e6a499f works for you please

**Comment by finferflu** [comment]
Hi @ucirello,

Thanks for the quick response. I have tried with `ed2a3ee` but I'm getting exactly the same issue, unfortunately.

**Comment by ucirello** [comment]
@finferflu -- I updated the documentation to reflect the need for the wait. Mostly, I wanted to avoid a situation in which I had to cover all the possible reasons that the table creation could fail. I know it is not the best solution, but I think it can do for now.

**Comment by finferflu** [comment]
@ucirello That makes sense. I'm not planning to use that feature myself, so this doesn't really affect me, but I just thought I'd flag it. Thanks!
