### ISSUE TITLE
Heartbeat will not start when a lock is acquired if it was recently stopped

### ISSUE THREAD

**Issue by kevin535nivek** [cirello-io/dynamolock#14]
We are seeing a lot of lock release failures in our application. After turning on the logs and digging through the code, this problems seems to trace back to a bug in the heartbeat code. When all locks are returned and the heartbeat goroutine exits, if a lock is immediately acquired, the `lastHeartbeat` is too recent to start another heartbeat. Because `enforceHeartbeat()` is only called when a lock is acquired, that lock will potentially expire unless another lock is acquired that can start the heartbeat in time.

```
func (c *Client) enforceHeartbeat() {
	if c.heartbeatPeriod == 0 {
		return
	}

	c.mu.Lock()
	defer c.mu.Unlock()
	lastHeartbeat := c.lastHeartbeat
	isHeartbeatDead := time.Since(lastHeartbeat) > 2*c.heartbeatPeriod
	if isHeartbeatDead {
		go c.heartbeat()
	}
}

func (c *Client) heartbeat() {
	c.logger.Println("starting heartbeats")
	tick := time.NewTicker(c.heartbeatPeriod)
	defer tick.Stop()
	for range tick.C {
		touchedAnyLock := false
		c.locks.Range(func(_ interface{}, value interface{}) bool {
			touchedAnyLock = true

			lockItem := value.(*Lock)
			if err := c.SendHeartbeat(value.(*Lock)); err != nil {
				c.logger.Println("error sending heartbeat to", lockItem.partitionKey, ":", err)
			}

			return true
		})
		if !touchedAnyLock {
			c.logger.Println("no locks in the client, stopping heartbeat")
			return
		}
		c.mu.Lock()
		c.lastHeartbeat = time.Now()
		c.mu.Unlock()
	}
}
```

This can possibly be fixed by resetting the `lastHeartbeat` to 0 time before the heartbeat stops so that it doesn't prevent another heartbeat thread from starting up.

**Comment by ucirello** [comment]
Thanks for the reporting. Could you please provide a reproduction case in code of this failure?

**Comment by kevin535nivek** [comment]
I was going to provide some code to reproduce it later, but it looks like you already made a patch with a  test that checks this failure case. Thanks for the quick response.

**Comment by macdonsp** [comment]
This can also create a goroutine leak if the iteration that goes through all of the locks is slow, and c.lastHeartbeat doesn't get updated in time, another goroutine will be created. The will both continue to exist until all locks are removed

**Comment by ucirello** [comment]
@macdonsp could you please open another issue?
