### ISSUE TITLE
Support for aws-sdk-go-v2 ?

### ISSUE THREAD

**Issue by obitech** [cirello-io/dynamolock#151]
Hello, is there any plan for a v2 release with support for the [aws-sdk-go-v2](https://github.com/aws/aws-sdk-go-v2) ? I'd be happy to help with contributions.

**Comment by obitech** [comment]
As a starting point for discussions, I've created #152 -- would love to hear your feedback on this!

**Comment by ucirello** [comment]
Hey @obitech -- Thanks for this issue and the opened PR. Per usual, I prefer people to discuss matters first before opening a PR to avoid frustration and confusion. 

You may notice that this repository is a mirror of the original source, and I am already working on the support for SDK v2 on the original source. 

The challenge has been so far how much of backward compatibility I want to bring about to the new version. Upgrading the dependency to v2 has ripple effects on the rest of the interface, creating a challenge from BC angle. It means that I might need to do a version bump and keep both v1 and v2 and then create a maintenance burden to myself. 

The good news, for me at least, is to see that you made similar decisions to the ones I made - like using helper functions to operate on attribute values. Also, I see a bit of divergence of values - like the use of "must*" pattern in tests. I see tests also as sources of example and the "must*" patterns, in my opinion, should be used sparingly. 

Although I don't intend to discourage you from contributing, I do plan to merge my changes first and you might find yourself rebasing a lot of your work.

Unfortunately, with the shutdown of the native Dependabot and free Travis, a lot of my attention has been drawn to replace these infrastructural shortcomings first, hence the delay for the SDK v2-compatible to be out.

**Comment by obitech** [comment]
Thanks for your quick response! I completely understand where you're coming from and the MR is merely for discussion, I don't expect it to be merged in that state 🙂 
Do you need help with CI migration? I could do a PR with migrating everything to Github Actions, if you like.

**Comment by ucirello** [comment]
@obitech thanks for the generous offer - please refer to https://github.com/cirello-io/dynamolock/pull/135#issuecomment-782564328

I am OK with porting the CI to some other platform as long as it is not Microsoft-owned. Thanks again!

**Comment by obitech** [comment]
Alright, I've created a new issue for the CI/CD migration, we can discuss there. I'll close my PR for time being.

**Comment by ucirello** [comment]
I merged in the work that I was doing at the main repository. Also, I decided to break this project away from the main repository as it is more used that I thought it was. I do not think tying its lifecycle to other lifecycles is a good idea anymore.

I am going to remove the '[Mirror]' annotation and promote it to standalone.
