### ISSUE TITLE
Migrate to new CI/CD platform

### ISSUE THREAD

**Issue by obitech** [cirello-io/dynamolock#153]
As mentioned in #151, I want to start a discussion about the CI/CD solution for this project (since Travis has been made unusable 😞 ). I know this repo is part of a bigger private monorepo, but I just assume we can implement CI for just this repo, or you can port over these changes to your own files as well (please correct me if I'm wrong tho!)

## Requirements 
- Run main tests with two containers: DynamoDB and the actual code
- Test-Matrix for multiple Go-Versions
- Ideally not from Microsoft

## Options
Service|Pricing|Limitations
---|---|---
[CircleCI](https://circleci.com)|Free for OSS|2,5k credits, 1 Job at a time, no macOS|
[Semaphore](https://semaphoreci.com)|Free for OSS|1300 minutes a month, 1 job at a time
[JFrog Pipelines](https://jfrog.com/pipelines/)|Free tier|2k minutes a month, feels very enterprisey

I think these are the viable options when it comes to SaaS, there is also [Buildkite](https://buildkite.com) and [DroneCI](https://drone.io) which look quite powerful but they require at least some part to be hosted on self-managed infrastructure.

All services have a YAML-configuration and seem to support all our required features.

@ucirello WDYT?

**Comment by ucirello** [comment]
> Ideally not from Microsoft

Ideally from standalone companies, not subsidiaries of bigger companies. 

I like Buildkite - especially because their deployment model do not force me to pollute the repository with company specific files that feel as laptop stickers (like `.github`, `.travis.yml` etc.)

**Comment by obitech** [comment]
Buildkite would require some dedicated infrastructure to install the agent and run the tests. Do you have a setup that would support this?

**Comment by ucirello** [comment]
@obitech -- I am going to check if I can get the resources in some affordable way and get back to you. I might run a sandboxed ARM agent somewhere. I want to make sure that we don't end up running crypto-mining attacks by accident.

**Comment by ucirello** [comment]
An update. I am waiting for the delivery of a Raspberry Pi to run the BK agent. As soon as I have more updates, I'll share them here.

**Comment by ucirello** [comment]
Addressed by https://github.com/cirello-io/dynamolock/commit/9b27c370a0ba19ad1543277349a845705cf2e3a7#diff-fb04dcb6970e4c3d1873de51fd5a50d7bb46b3383113602665c350ec40b5f990
