### ISSUE TITLE
Add Makefile and docker-compose.yml for easier testing

### ISSUE THREAD

**Issue by obitech** [cirello-io/dynamolock#154]
I would like to improve the test workflow:

1. Add a `docker-compose.yml` with DynamoDB. This is for local development only.
2. Add a `Makefile` which brings up the DynamoDB as well as runs tests via `make test`.

Happy to discuss the details here and submit a PR :)

**Comment by ucirello** [comment]
I'd like to move away from containerized solutions - especially to avoid hitting rate limits. 

As of https://github.com/cirello-io/dynamolock/commit/6fc3fdebc67e40aea9331982f06703bd0993dac0 - I included a Makefile that downloads the binary. The test files now have a `TestMain` that starts and stops the local dynamodb lock used for testing.

**Comment by obitech** [comment]
Ok nice 👍
