### ISSUE TITLE
Introduce different logging level for each message

### ISSUE THREAD

**Issue by or-shachar** [cirello-io/dynamolock#155]
Currently the v2 client prints everything using the same `Println` function, no matter if the print is meant for debug, info or error. This makes it hard to filter significant log lines in production.

WDYT changing the `ContextLogger` a bit so it can support printing status Info / Debug or Error?

**Comment by ucirello** [comment]
Hi @or-shachar -- thanks for opening this issue.

I do not fundamentally oppose your idea, but at the same time, whenever I tried to add message level support to the internal logger, what I realized is that the messages rarely make sense in different level. Usually, what happens for me in the cases I have this deployed in production is that I want the whole clockwork messages exposed at a certain level, at times DEBUG, at times INFO -- it really depends on the context.

Could you please elaborate what messages would you put in what level?

**Comment by or-shachar** [comment]
I understand your point. For the very least I'd separate between `INFO/DEBUG` and `ERROR`.

Our use case is simple - when monitoring production there are different log retention rules per log level. 
Messages like [this](https://github.com/cirello-io/dynamolock/blob/master/client.go#L354) are very debug-like IMO and do not provide value unless you want to actually debug a problem. Messages like [this](https://github.com/cirello-io/dynamolock/blob/master/client.go#L684) indicate that there's a problem. They need to be saved for a longer time.

**Comment by ucirello** [comment]
@or-shachar I see where you are getting at. If anything, perhaps the right solution is to remove log messages not grade them, what do you think?

**Comment by or-shachar** [comment]
That's one direction and that would be easy for us to implement a logger that does nothing on `Println`.

I do think it's valuable to allow the users to monitor and alert according to errors log messages so I wouldn't advise dropping those.

**Comment by ucirello** [comment]
I think I am stuck here. Because to add graded messages, I would probably have to make a non-BC change, or make the current interface more unwieldy. 

Also removing messages, might become problematic because it would break the natural Go stability promise. 

I think you have a very valid suggestion for a v3. I'll take that in consideration for the next major release.

**Comment by or-shachar** [comment]
Sounds reasonable! We'll wait for v3 for that.
In the meantime - I'll implement some hacky logger that would find the keyword `error` in the printed message and route it to the right level in our internal logger.

Thanks for your quick response! : 🙏

**Comment by ucirello** [comment]
@or-shachar could you please test: 7de69a368a1d7b49d67818912103466475a7d9db

**Comment by or-shachar** [comment]
Hey @ucirello  - thanks for this... I'll try to test it
