### ISSUE TITLE
Add Sort Keys

### ISSUE THREAD

**Issue by sw-square** [cirello-io/dynamolock#157]
(Continued from https://github.com/cirello-io/dynamolock/pull/156#issuecomment-991162872)

It'd be quite helpful to have support for sort keys on locks. Our use case at Square is implementing a distributed load-balancing system, where locks are used to indicate that a shard is currently owned. To enable workers to pick up slack from peers that leave, we need a way to efficiently enumerate all locks that are currently a part of the sharded pool. Adding sortkeys would make this a lot easier (the partition key is the pool's name, whereas the sort key is a UUID for each worker). 

As @Zellyn mentioned, I've been working on a PR for this, which is fairly unintrusive:
- Having an empty `sortKey` functions the way it currently does
- If a `sortKeyName` is provided on Client creation, then it's required (via `WithSortKey`) whenever a lock is acquired.

**Comment by ucirello** [comment]
> If a sortKeyName is provided on Client creation, then it's required (via WithSortKey) whenever a lock is acquired.

Require or made default?

**Comment by sw-square** [comment]
It's required if a `sortKey` was passed to the `Client` when it was created, and disallowed if no `sortKey` was passed to the `Client`: 

```go
// InvalidSortKeyNameError is an error that's used to indicate that either a sort key was expected and not given,
// or was given and not expected.
var (
	// SortKeyExpectedError indicates that a sort key was passed to AcquireLock (or AcquireLockWithContext), but was
	// not provided in the constructor of the Client.
	SortKeyNotExpectedError = errors.New("sort key given when none was expected")

	// SortKeyExpectedError indicates that no sort key was was passed to AcquireLock (or AcquireLockWithContext), but
	// one was provided in the constructor of the Client (and thus, is required).
	SortKeyExpectedError = errors.New("sort key expected when none was given")
)

func (c *Client) hasSortKey() bool {
	return c.sortKeyName != ""
}

func (c *Client) storeLock(ctx context.Context, getLockOptions *getLockOptions) (*Lock, error) {
	// Ensure that the sortKey is only given when we expect it.
	if !c.hasSortKey() && getLockOptions.sortKeyName != "" {
		return nil, SortKeyNotExpectedError
	}

	if c.hasSortKey() && getLockOptions.sortKeyName == "" {
		return nil, SortKeyExpectedError
	}
	...
}```

**Comment by ucirello** [comment]
Could you please share how the new client signature would look like?
``` dynamolock.New(...., dynamolock.EnforceSortKeys()) ```?

**Comment by sw-square** [comment]
Sure. Something like this:
```go
// creating the dynamolock client
dynamoDB := dynamodb.NewFromConfig(...)
client, err := dynamolock.New(dynamoDB,
	"tablename",
	dynamolock.WithHeartbeatPeriod(...),
	dynamolock.WithLeaseDuration(...),
	dynamolock.WithSortKeyName("sortKey"))

// acquiring a lock
lock, err2 := client.AcquireLock("partitionName",
	dynamolock.WithData(data),
	dynamolock.FailIfLocked()
	dynamolock.WithSortKey("sortName"))

```

**Comment by ucirello** [comment]
@sw-square I think I see what you mean. I like the concept and the intention, but I think we need to iterate the solution further. 

I want to avoid the situation in which you only realize that something is wrong when it is already too late. Or in different terms, by making a client with `WithSortKeyName` and erroring out if `WithSortKey` is missing, we'd be relying on the runtime to catch an error, in other words, too late.

You may see that I didn't issue a release right after @sysadmind contribution because I am still wrapping my mind around the concept (https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-sort-keys.html).

Assuming you had free reigns, how would you reshape the interface to make such errors evident during compilation time rather than runtime?

**Comment by zellyn** [comment]
I don't think you can catch sortkey presence mismatches at compile time, just like you can't notice partition key column name mismatches at compile time. After you create the client, things should just work - a missing sort key would turn into an empty string, which should be fine.

**Comment by ucirello** [comment]
why not?
```Go
// creating the dynamolock client
dynamoDB := dynamodb.NewFromConfig(...)
client, err := dynamolock.NewWithSortKey(dynamoDB,
	"tablename",
        "sortKeyFieldName",
	dynamolock.WithHeartbeatPeriod(...),
	dynamolock.WithLeaseDuration(...))

// acquiring a lock
lock, err2 := client.AcquireLock("partitionName", "sortName",
	dynamolock.WithData(data),
	dynamolock.FailIfLocked())
```

**Comment by sysadmind** [comment]
Would NewWithSortKey not necessitate a new client type that has different method signatures for calls like `AcquireLock` in order to achieve compile time validation? 

Would that make it harder to develop/use the client because now there must be 2 copies of all of the methods (one for the existing client and one for the new client type)?

**Comment by ucirello** [comment]
@sysadmind that's a trade-off for sure. I am not fundamentally opposed to having a second set of interfaces, as long as it make it compile-time safe.

Try to keep in mind what happens with a typical Go developer:
```
sth, err := obj.DoMagic()
if err != nil{
        return err
}
```

Typically, gophers still don't check for what type of error they get. They just assume an error is an error and stop. If we keep things optional, we are going to have two very distinct classes of error, instead of one: a) clockwork error - something did not go well when running the code; b) you did not use this package correctly error.

With the typical `if err != nil` approach, people will not have the natural intuition of what could be going wrong.

**Comment by sw-square** [comment]
You're definitely right that a mismatch doesn't _feel_ like a runtime error, but I don't think creating a whole extra type is the best way to go: Not only does it complicate the interface, but it also increases maintenance load.

I think a good compromise would be to simply `panic` if there's a sortkey mismatch, since  mismatch is definitely indicative of programatic error. Not quite as good as a compile time error, but it's something that you definitely cannot just swallow up and ignore.

**Comment by ucirello** [comment]
I see your point. Well, the constraint I am imposing is no runtime surprises. Using panic() actually makes the situation worse by killing the routine executing this code.

So runtime enforcement is ruled out as far as I am concerned. Now the question becomes how we should design this interface to not be redundant and compilation-time safe.

You made a claim I do not follow. Why a second type just for sort keys will make the maintenance harder?

**Comment by zellyn** [comment]
I believe we could make it no worse than it is right now with regard to runtime problems. Right now, if you try to create a lock, and there is no DynamoDB table, or it has the wrong schema, you'll get an error, so there are _some_ runtime error cases.

The following should cover the cases that can happen when creating locks:

|   | Lock is created without sort key | Lock is created with sort key |
| --- | --- | --- |
| **Client is created without sort key** |  Normal, no sort key  | Sort key is ignored |
| **Client is created with sort key** | Sort key of `""` is used | Normal, with provided sort key |

In the case of a mismatch, we can just ignore the sort key, or use an empty string. Either way, no runtime errors.

Here are the cases that can happen when creating clients:

|   | Table doesn't exist or has wrong schema | Table exists with no sort key | Table exists with sort key |
| --- | --- | --- | --- |
| **Client is created without sort key** |  Same error as current code  | Normal | Treat as wrong schema |
| **Client is created with sort key** | Same error as current code | Treat as wrong schema | Normal |

**Comment by ucirello** [comment]
> there are some runtime error cases.

Two cases here: a) the clockwork has a problem, b) the library wants to validate the programmer did the right thing. 

I have no problems with runtime safety for (a); I want to stop expanding (b) (for example: https://github.com/cirello-io/dynamolock/blob/v1.4.0/client.go#L106-L110).

@zellyn - you presented two truth tables. Both of them do not make (a) worse. And your solution seems to not expand on (b). Which can be barely enough for me. 

Now - you made a trade-off. You traded compilation-safety for surprise. How surprising will be the first truth table. 

If the client is created without a sort key, then, by absence of mind I create a lock with a sort key - then the client will silently misbehave. Which takes me to the point that I wanted to make with a separate set of interfaces: one for client with sort key, impregnating the need at interface level everywhere; and another one without. 

I wonder if we could keep just on structure for everything, but make AcquireLock to return an interface-typed value that forces the caller to assert the type. So let's run the options here:

Option 1: return error on acquisition if sort keys are used on incorrectly configured client.
```Go
cl , err := dynamolock.New(...)  // no sort key name declare, next line is going to fail
l, err := cl.AcquireLock("lock", dynamolock.WithSortKey("sortKey"))
if dynamolock.IsMissingSortKey(err){
    return fmt.Errorf("client is misconfigured: %w", err)
} else if err != nil {
    return err
}

```

Option 2: Use Specific Interface everywhere
```Go
cl , err := dynamolock.NewWithSortKey(...) 
l, err := cl.AcquireLock("lock", "sortKey")
if err != nil {
    return err
}
```

Option 3: Use interface-types to force using to assert type before use (not so different from what GRPC-go does)
```Go
cl , err := dynamolock.New(...)  // no sort key name declare, next line is going to fail
l, err := cl.AcquireLock("lock", dynamolock.WithSortKey("sortKey"))
if err != nil {
    return err
}
// either
var sortKey *dynamolock.LockSort
if !dynamolock.As(l, &sortKey) {
    return errors.New("not a lock with a sort key")
}
// or
sl, err := dynamolock.LockSort(l)
if err != nil{
    return err
}
// or even
// the client AcquireLock doesn't fail and you get surprised when you realized that it ignored one of the configuration options because you misconfigured the client.
```

**Comment by ucirello** [comment]
@zellyn -- I am OK with the automagic option for now. One possible escape valve for possible confusion is that I can alway log a misconfigured `AcquireLock` with error level.

**Comment by zellyn** [comment]
@ucirello let me re-articulate your "two types" approach and see if I understand.

We'd move most `Client` methods into a common internal class, say `internalClient`.

Then we'd have

```go
type Client struct {
  internalClient
}

type ClientWithKey struct {
  internalClient
}
```

`internalClient` would implement most [Client methods](https://pkg.go.dev/cirello.io/dynamolock/v2#Client):
* Close
* CloseWithContext
* CreateTable
* CreateTableWithContext
* ReleaseLock
* ReleaseLockWithContext
* SendHeartbeat
* SendHeartbeatWithContext

`Client` and `ClientWithKey` would implement the rest:
* AcquireLock
* AcquireLockWithContext
* Get
* GetWithContext

Is that right?

**Comment by ucirello** [comment]
If not exactly that, pretty close. I am not sure whether CreateTable would have to be forked or not.

**Comment by sw-square** [comment]
When I was writing my PR, I found it weird that `CreateTable` had an option to specify a partition key name, when it should (I think?) default to whatever the client's partition key was

**Comment by ucirello** [comment]
@sw-square my idea was to have a method that would assist people to create the table the right way. As of now, I consider it a design mistake and I would be more than happy to drop this method in V3.

**Comment by zellyn** [comment]
It turns out [sort key cannot be empty](https://aws.amazon.com/about-aws/whats-new/2020/05/amazon-dynamodb-now-supports-empty-values-for-non-key-string-and-binary-attributes-in-dynamodb-tables/). So the `ClientWithKey` would need to return errors if you pass in empty sort keys. That seems fine.

**Comment by ucirello** [comment]
OK. Whatever path I choose here, it is going to be a rather large refractor.

I'm going to be able to work on it only in January.

**Comment by sw-square** [comment]
I'd be happy to work on a PR and then submit it, if you're amenable to it

**Comment by ucirello** [comment]
@sw-square let me prepare a dynamolock/v3 and then we ship it in the v3

**Comment by ucirello** [comment]
@sw-square please, share with me a vision of how you are going to approach the build of this feature. It seems that the automagic version that bubbles up the Sort Key constraint errors straight from the DynamoDB API is what we are favoring here.

Because it is a major version bump, you have a bit more room to make backward compatible changes, but make them sparingly please.

Favor a string of small PRs instead of a large one. I tend to work better with smaller review cycles instead of a big one.

**Comment by sw-square** [comment]
After discussing with @zellyn, we've decided that if you're up for it, option 2 would be best. To do this, we'd change the type definitions from
```go
type Client struct {
	dynamoDB DynamoDBClient
	...
}
```
to
```go
type internalClient struct {
	....
}

type Client { internalClient }
type ClientWithKey { internalClient }
```.
We'd implement all operations that the two share (Close, Release, etc) in the base `internalClient`, as well as the meat of of the two divergent functions. So, in essence we'd have something like `AcquireLockWithContext` implemented like this:
```go

// AcquireLockWithContext holds the defined lock. The given context is passed down to the underlying dynamoDB call.
func (c *Client) AcquireLockWithContext(ctx context.Context, partitionKey string, opts ...AcquireLockOption) (*Lock, error) {
	return acquireLockWithContext(ctx, partitionKey, "", opts...)
}

// AcquireLockWithContext holds the defined lock with the given sortKey. The given context is passed down to the underlying dynamoDB call.
func (c *ClientWithSortKey) AcquireLockWithContext(ctx context.Context, partitionKey, sortKey string, opts ...AcquireLockOption) (*Lock, error) {
	return acquireLockWithContext(ctx, partitionKey, sortKey, opts...)
}


func (c *Client) acquireLockWithContext(ctx context.Context, partitionKey, sortKey string, opts ...AcquireLockOption) (*Lock, error) {
	if c.isClosed() {
		return nil, ErrClientClosed
	}
	req := &acquireLockOptions{
		partitionKey: partitionKey,
		sortKey:      sortKey,
	}
	for _, opt := range opts {
		opt(req)
	}
	return c.acquireLock(ctx, req)
}
```
With this, there'd be no changes to people sing `Client` (except maybe deprecating `WithCustomPartitionKeyName`, as it's definedj within the `Client`'s constructor), and people could use the new `ClientWithSortKey` type in almost the exact same way: Whenever you'd just pass a key to a `Client` method, you'd pass that key and the sortKey to the `ClientWithSortKey`'s method.

**Comment by ucirello** [comment]
@sw-square v3 package is open

**Comment by sw-square** [comment]
Slight nudge to see if you're working on this; if not I'm happy to do it myself.

**Comment by ucirello** [comment]
@sw-square go ahead. I am going to reinforce what I wrote before:

> Favor a string of small PRs instead of a large one. I tend to work better with smaller review cycles instead of a big one.

**Comment by sw-square** [comment]
Sounds good :+1:

**Comment by ucirello** [comment]
@sw-square as a follow up for https://github.com/cirello-io/dynamolock/pull/160, I suggest we drop CreateTable.

**Comment by sw-square** [comment]
@ucirello I like that idea, but I think there should be some way to opt out of creating the table—maybe through another `ClientOption`?

**Comment by ucirello** [comment]
@sw-square - I think the table creation should be gone altogether. The client would only connect and do lock handling. Table creation would become a manual operator - as often is anyway.

**Comment by sw-square** [comment]
As in removed from `dynamolock` entirely, or just as part of `Client`?

**Comment by ucirello** [comment]
removed from `dynamolock` entirely.

**Comment by zellyn** [comment]
I felt the same way — that table creation is better done in terraform, or the equivalent — but adding functionality to create the table if absent on first use was added in short order to both our Go and Java wrappers… people seem to like it. I think it would be better for it to remain in `dynamolock`, and then people can decide which approach they prefer.

**Comment by ucirello** [comment]
@zellyn - we can always add it later. I am going to open an issue to track it.

**Comment by ucirello** [comment]
Ping @sw-square any updates?

**Comment by ucirello** [comment]
Ping @sw-square @zellyn 

If you cannot proceed further with this refactor, please let me know.

**Comment by ucirello** [comment]
Ping @sw-square @zellyn

OK, it seems this line of work is abandoned.
