### ISSUE TITLE
Evaluate the decision of keeping/removing `CreateTable`

### ISSUE THREAD

**Issue by ucirello** [cirello-io/dynamolock#161]
refer to https://github.com/cirello-io/dynamolock/issues/157#issuecomment-1005196692

**Comment by sw-square** [comment]
I think that the `CreateTable` function is a good helper function in concept, as it's setting up the table in exactly the way dynamolock is expecting it. There's a few things that could be tweaked (eg not requiring you to pass the `tableName`, as that's already given through the `commonClient`), but I think overall it's definitely helpful

**Comment by ucirello** [comment]
Keeping the interface as it is.
