### ISSUE TITLE
Require `partitionKeyName` in `New`.

### ISSUE THREAD

**Issue by sw-square** [cirello-io/dynamolock#172]
It feels a bit awkward that `New` does not require a `partitionKeyName`, while `NewWithSortKey` requires a `sortKeyName`. I propose we change the interfaces from
```go
func New(dynamoDB DynamoDBClient, tableName string, 
	opts ...ClientOption) (*Client, error) { ... }

func NewWithSortKey(dynamoDB DynamoDBClient, tableName, sortKeyName string,
	opts ...ClientOption) (*ClientWithSortKey, error) { ... }
```
to
```go
func New(dynamoDB DynamoDBClient, tableName, partitionKeyName string, 
	opts ...ClientOption) (*Client, error) { ... }

func NewWithSortKey(dynamoDB DynamoDBClient, tableName, partitionKeyName, sortKeyName string,
	opts ...ClientOption) (*ClientWithSortKey, error) { ... }
```

This way, the interface is more uniform, as well as we no longer have `WithPartitionKeyName`. To the end user, there wouldn't be much difference, as all they'd have to do is supply a field such as `"lock"`.

**Comment by ucirello** [comment]
The initial inspiration was the idea to reuse the same client to multiple locks. When a system needs to coordinate multiple locks, in a very large scale, the pressure to make the client lightweight increases. By moving all the requirements to the constructor, it improves the API but it might penalizes that multitude-of-locks use case.

For v3, I am ok with merging this interface and give it a try. If it doesn't pan out well, we can redesign the interface and remove it.
