### ISSUE TITLE
Add support for dynamodb ttl

### ISSUE THREAD

**Issue by forGitMeNotPlease** [cirello-io/dynamolock#199]
Would it be possible to add something where we can set a ttl if we wanted to enable it? These locks just end up hanging around forever, it would be nice if we can use dynamodb ttl to clean em up.

**Comment by ucirello** [comment]
I would have to dig deeper before I try and implement this idea. I am not sure if the DynamoDB TTL feature would play well with the expectation that this library has about the resources always being there. I am going to dig further and get back later.

**Comment by ucirello** [comment]
I am not fundamentally against this idea, but the more I dig the less obvious it is for me to conciliate the locks TTL with the entry in DynamoDB TTL. I am going to mark this issue as v3, but I will give it a try some time the next week to see if I can come up with something that at least works well. My main fear is the footgun of people setting DynamoDB entry TTL that removes the entry from the database while the clock is catching up somehow. It would have to be a period long enough that it wouldn't collide with the client manipulating the lock.

**Comment by forGitMeNotPlease** [comment]
Thank you for considering this. In our case, records that would be 'worked on' would only hang around for ~5 days and after that, they just go out of scope. So we would set it to when the record would expire, but I understand your main fear there with prob the majority of other's use cases.

**Comment by ucirello** [comment]
@forGitMeNotPlease ping

**Comment by forGitMeNotPlease** [comment]
Sorry for the delay. This works absolutely fine. Tested it out today 👍. Thank you!

**Comment by ucirello** [comment]
Great!
