### ISSUE TITLE
Follow up on serialisation

### ISSUE THREAD

**Issue by rmancy-canva** [cirello-io/dynamolock#206]
Hello. I was looking to see what kind of support there was for serialisation. I came across an [old question](https://github.com/cirello-io/dynamolock/issues/83) regarding this (since closed) that had no real resolution. My use-case seems to be very similar (if not the same) to the one highlighted in that issue, so I might just reply to the points made in response to it.

>it seems that you have a sequential pipeline and you'd want to rely on a single lock to coordinate the hand-over between the steps of this pipeline. 

Yes

>If I understood you correctly, none of those propositions would work.

 :-(

>Serializing the current state of the lock only works if the hand-over doesn't happen on the verge of the heartbeat. If some other entity is competing for the lock, and then you serialize it and hand it over to the next step, the first entity is going to grab the lock and you are going to hand a stale-but-looking-good lock.

This is a real concern for sure. Would a simple solution for this be to ensure that you heartbeat after re-serialising? If the lock has expired the heartbeat should fail. You could build this into the package itself, within `AcquireSerializedLock` or something.   

>Also, using the client owner as the proxy of lock ownership is a brittle proposition, because it relies on the need of a human not making a mistake of deploying two clients with the same owner. 

Yes, but AIUI the forced heartbeat should solve this shouldn't it? You could distribute that lock to dozens of clients, they would deserialise the lock, they would then heartbeat, but only one of them will set the new rvn. The rest will fail [here](https://github.com/cirello-io/dynamolock/blame/c4fc08f1a250d7233e38869e2384eed9ef3ffb5f/v2/client_heartbeat.go#L113) when they try to update the lock with the now old rvn. Thus, they will fail to acquire the lock. 

>I have seen it more often fail than succeed. That's why this current design doesn't rely on the owners for decision making -- owners are useful for inspection, to understand what entities of your systems are doing.

The decision by the original owner in this case when they serialise and publish the lock, is that the lock is up-for-grabs, and that they may lose it. This doesn't seem overly different from current decisions that owners of locks make (i.e releasing and getting locks).

>From what I gather, what you need is to use the Lock as mutex and not as wait-queue.My suggestion then is: store the current step of the processing in a number in DynamoDB and use this library to coordinate its updates and reads. Each step, before starting, grabs the lock and reads the number -- if this number corresponds to the step that needs to be executed, you update the number, release the lock and proceed. If the numbers don't match, you release the lock and try again

Hmm, how do you 'grab the lock' in this case though? You can read it for sure, but grabbing it implies that you own the lock (which is what you'd need serialisation for, as the steps don't share the same process space). I suspect you mean that they're creating and releasing new locks. This may work in some scenarios, but not in mine. Basically I want service A to work mutually exclusive to service B. Service A is broken up into multiple tasks, and I want those tasks to be able to control that lock to keep service B out (and to release early if they need to). If each service A task has to create and release the lock, that gives multiple windows for service B to take control. Service B doesn't care about the numbering or any service A specific logic in this case.

Apologies if I've still mis-understood something.

**Comment by ucirello** [comment]
hi @rmancy-canva -- thanks for opening this issue.

The real problems is always making sure that you can reason about who is the current holder of the lock. Feel free to deploy the client however you like as long as you can later reason about why two competing clients knocking each other off. If they don't, you're in the clear. If they do, the solution lies in designing the system for optimistic locking rather than changing the properties of this library. 

Good luck!
