### ISSUE TITLE
GetWithContext always return ReadOnly lock

### ISSUE THREAD

**Issue by karol-janik** [cirello-io/dynamolock#312]
Hi there! 
I'm wondering why does the `GetWithContext` always returns a `ReadOnly` lock ([updates RVN to ""](https://github.com/cirello-io/dynamolock/blob/master/v2/client.go#L991))? 🤔

The [docs](https://github.com/cirello-io/dynamolock/blob/v1.4.0/client.go#L922) says that I should be able to release a lock after a get operation (if the client owns lock and my owns), but based on my tests it's not true. Maybe I missed something?

My use case:
I'd like to hide the implementation details of `DynamoLock` and create a function that based on the key will Get the lock and Release it.

**Comment by ucirello** [comment]
Hi @karol-janik -- thanks for the bug report. I restored the original behavior and fixed the documentation accordingly (the previous phrasing was confusing about lock ownership -- it's not only a matter of who the `client.ownerName` is, but also whether the client still have the pointers.)

**Comment by ucirello** [comment]
Please, validate with 030c85ea01d94e73fffab891e4ffb239054217af
