### ISSUE TITLE
WithSessionMonitor does not work as expected

### ISSUE THREAD

**Issue by allanliu** [cirello-io/dynamolock#446]
Hi,

tag: 2.0.3

I've recently started using this client library and have noticed some of the interfaces do not work as expected, most importantly [WithSessionMonitor's](https://pkg.go.dev/cirello.io/dynamolock/v2#WithSessionMonitor) callback never gets invoked even when the client completely loses its connection with the underlying DynamoDB lock table. I simulated this within a K8s pod in which I used `iptables` to reject all messages to and from the DynamoDB IP range, and the call back never gets invoked. An example of the code is:
```go
	c, err := dynamolock.New(dynamodb.NewFromConfig(cfg),
	        "some-service.locks",
		dynamolock.WithLeaseDuration(10 * time.Second),
		dynamolock.WithHeartbeatPeriod(3 * time.Second),
		dynamolock.WithOwnerName(hostname),
	)
	if err != nil {
		return nil, errors.Wrap(err, "failed to create dynamolock client")
	}

...

                 // Chan used to signal lock is close to expiration
		done := make(chan struct{})
		lock, err := c.AcquireLockWithContext(ctx, c.lockKey,
			dynamolock.WithDeleteLockOnRelease(),
			dynamolock.WithSessionMonitor(10*time.Second, func() {
				glog.Warning("session monitoring triggered alert for lock approaching expiration, will release and try to acquire again")
                                   // THIS CODE IS NEVER REACHED
                                  // Close the channel
				close(done)
			}),
		)
		if err != nil {
                     ...

			select {
			case <-ctx.Done():
				return nil
			case <-done:
				return errors.New("lock expiring")
			}
```

Please let me know if there's anything else I can provide. Would love to know if I'm doing something wrong here or how we can get this issue resolved. I'll file another issue for the other issues I have reproduced. Thanks!

**Comment by ucirello** [comment]
@allanliu - Thank you for opening this issue. 

In your example, the `WithSessionMonitor` duration overlaps with `WithLeaseDuration` duration - as it is, you're never going to get into the danger zone, and the callback will never be called. 

I issued similar test here (both using firewall to kill network packets, and SIGSTOPping the DynamoDB test server) -- and it works when I use a `safeTime` that's a multiple of Heartbeat and lower than `LeaseDuration`. 

I hope this information helps you.

**Comment by allanliu** [comment]
@ucirello 

I just tried to simulate the issue with a lease duration of `10 * time.Second`, a hearbeat of `2 * time.Second` and a session monitor safe time of `6 * time.Second`, and the `WithSessionMonitor` callback still did not get invoked. Is there anything that I'm missing here?

**Comment by ucirello** [comment]
I wonder if there are other factors in place that you might be missing. Can you provide me with a minimal and consistent reproduction case?

**Comment by allanliu** [comment]
Yes of course.
The code equivalent (simplified for easier reproduction)
```go
        ctx := context.Background()
	hostname, err := os.Hostname()
	if err != nil {
		return nil, errors.Wrap(err, "failed to get OS hostname")
	}
	cfg, err := aws_config.LoadDefaultConfig(ctx, aws_config.WithRegion("us-east-1"))
	if err != nil {
		return nil, errors.Wrap(err, "failed to load AWS config")
	}
	c, err := dynamolock.New(dynamodb.NewFromConfig(cfg),
	         "test.locks",
		dynamolock.WithLeaseDuration(10 * time.Second),
		dynamolock.WithHeartbeatPeriod(2 * time.Second),
		dynamolock.WithOwnerName(hostname),
	)
	if err != nil {
		return nil, errors.Wrap(err, "failed to create dynamolock client")
	}

        lockKey := "somekey"
       	for {
		done := make(chan struct{})
		lock, err := c.lockClient.AcquireLockWithContext(ctx, lockKey,
			dynamolock.WithDeleteLockOnRelease(),
			dynamolock.WithSessionMonitor(6*time.Second, func() {
                                 // This never executes.
				close(done)
			}),
		)
		if err != nil {
			if _, ok := err.(*dynamolock.LockNotGrantedError); !ok {
				return err			
                         }

		} else {
			defer func() {
				if err := lock.Close(); err != nil {
					glog.Warningf("error trying to close current lock: %v", err)
				}
			}()

			callbackCtx, cancelCallback := context.WithCancel(ctx)
			defer cancelCallback()
			go doWork(callbackCtx)

			select {
			case <-ctx.Done():
				return nil
			case <-done:
				return errors.New("held lock was lost (or close to it) likely due to heartbeat failure; " +
					"exiting to be safe.")
			}
		}

		glog.Info("lock was not granted, will try  again")
		select {
		case <-ctx.Done():
			return nil
		default:
		}
	}
...
```

Steps to reproduce:
1. Deploy 2 pods containing the go programs using LE client in EKS
2. Identify the k8s nodes the pods are scheduled on.
3. SSH into k8s node hosting the pod that is leading
4. Find the PID of that pod, and enter into the network namespace (with `nsenter -t <PID> -n`)
5. Use `iptables` to disrupt the connection to the backing DynamoDB table, e.g. `sudo iptables -A INPUT -s 35.71.64.0/22 -j REJECT`
6. Observe. You should see that the even when the socket connection is removed, the leader client is still not aware, and the callback for `WithSessionMonitor` is never invoked. You can verify on the client that is not leading that it will successfully acquire the lock after the lease duration is expired after the `iptables` rule update.

**Comment by ucirello** [comment]
Thanks for the code snippet.

I do not have an EKS cluster here, but I tried both in the shell using iptables and then using Docker. And the code behaves correctly when I use either REJECT or DROP. And I also tested on MacOS. 

In all cases, I placed the call to DynamoDB Service. 

At this point, I wonder the network layer semantics are not getting in the way somehow. 

You can see if the connection is actually going through or not by annotating the update call. In `func (c *Client) sendHeartbeat` you may add: 
```
	_, err := c.dynamoDB.UpdateItem(ctx, updateItemInput)
	if err != nil {
		fmt.Println(">>> You should see this when the network is interrupted... err:", err)
		return err
	}
	fmt.Println(">>> ... but in practice, you might be seeing this. Indicating that you may have not interrupted the connection the way you thought you did.")
```

And observe the logs -- it's tricky, because the name Amazon uses to block the connection resolves to multiple IPs, and it possible that the rage you used is not wide enough to sever the connection.

**Comment by allanliu** [comment]
Thanks, I'll try to add that print statement to confirm.

I'm pretty confident that the connection has been severed though as I have verified by observed no new tcp sockets established to the any of the DynamoDB IP ranges (with `ss -tn`) and also observed the "other" client to able to successfully acquire the lock on the same key after the iptables rule.

**Comment by allanliu** [comment]
Ok, so this was actually just an issue where there was no timeout set (default AWS client behavior). Because of the the timeout timeout duration is well beyond the lease duration. Could you please add this into the example code? 
```go
	cfg, err := aws_config.LoadDefaultConfig(ctx,
		aws_config.WithHTTPClient(http.NewBuildableClient().WithTimeout(500*time.Millisecond)),
                 ...
	)
```

Also, what are your thoughts on using a request time client timeout thru the context object (perhaps determined from the heartbeat period)? The heartbeat is such a critical part of the algorithm and seems to be a vector from which we get unexpected behavior where the ownership muddled and can't recover.

**Comment by ucirello** [comment]
I am glad that you managed to figure out the issue.

I am going to think about your suggestions when issuing the next release.

Thank you

**Comment by allanliu** [comment]
Thank you for assistance!

Just to add bit more to why I think the heartbeat timeouts should be independent. Generally speaking the core AWS session object is created near the entry point of the application and passed into different service clients. Most often the timeouts and retry logic are tied to this general purpose client usage that doesn't fit well with what's needed for heartbeats. For instance, using exponential backoff with even a reasonable short timeout duration, we can imagine a scenario in which the lease duration is exceeded outside view of the session monitor. Heartbeats should fail much faster, and it seems like it should be usually within heartbeat period itself.

**Comment by ucirello** [comment]
The reason that heartbeats have their own call is to allow corners cases to be handled individually, like the one you put forward. You can always use manual heartbeats instead of automatic ones.

**Comment by ucirello** [comment]
I think you might be referring to `WithSessionMonitor`? There is no `WithSessionCallback`. I dug this further, and I can consistently make it work, especially after tuning the timings to be higher than any total retry time of the underlying HTTP client. 

I set up a EKS cluster for testing, and when I block all the IPs at the node level, it also works. 

I must say I am skeptical. I won't go as far as to say that it is impossible to be a bug in the client, but so far, all my tests work. I would start looking around if some other logic/semantics happening at network level happening that you may not be aware of.

If you get an automated test case that I can run and reproduce the issue, please, open a new issue.
