### ISSUE TITLE
Getting contents of lock without acquiring the lock

### ISSUE THREAD

**Issue by aashishkapur** [cirello-io/dynamolock#52]
Hi, 
I was trying to get the contents of a lock without acquiring the lock, but found that when I tried to get the lock, 
```
lock, err = client.Get(dynamoLockName)
```
I received a lock with no data.

I looked into `Get`, and found that this branch was getting executed: https://github.com/cirello-io/dynamolock/blob/master/client.go#L906, because the lock is currently not held. Therefore, an empty lock is returned, with no data.

I'm happy to make a PR to fix this by removing the `lockItem.isReleased` check, but wanted to confirm.

**Comment by aashishkapur** [comment]
code snippet:
```
lock, err := client.Get("spock")
if err != nil {
	log.Fatal(err)
}

log.Println("lock content:", string(lockedItem.Data()))
//this is empty
```

**Comment by ucirello** [comment]
@aashishkapur thanks for the report. I suspect the code is working fine. I just reviewed the tests here, and they do seem to validate `Get()`. Could you provide a piece of code that proves the problem? 

Also, I suggest you refer to the test `TestReadLockContent` in client_test.go (https://github.com/cirello-io/dynamolock/blob/master/client_test.go#L149-L209) which shows how to use this feature.

**Comment by ucirello** [comment]
Hi @aashishkapur - I found the bug. Thanks for the report. The fix is merged.
