### ISSUE TITLE
AcquireLock fails if conditional lock creation fails

### ISSUE THREAD

**Issue by herzo175** [cirello-io/dynamolock#56]
Hello!

I'm running into this error when acquiring a lock:

`cannot store lock item: lock already acquired by other client: ConditionalCheckFailedException: The conditional request failed`

This seems to happen when multiple clients are waiting for a lock and the read request succeeds for at least 2 of them, causing the conditional lock put request to be invoked at the same time. My proposal is that the client should continue to retry if encountering this error.

I appreciate your work on this project and considering this request.

**Comment by ucirello** [comment]
Hi @herzo175 - I am afraid I don't understand your description of the problem. 

Could you please share a snippet that proves it?

**Comment by ucirello** [comment]
Fix published. Thanks for the report @herzo175

**Comment by herzo175** [comment]
Works great, thank you so much @ucirello !
