### ISSUE TITLE
Stale Additional Attributes

### ISSUE THREAD

**Issue by davidjumani** [cirello-io/dynamolock#8]
When Load testing, stale additional attributes are saved instead of the updated ones when acquiring the lock, due to a custom update during the time between the getItem and the putItem. Instead, could just use an updateItem when acquiring the lock instead ?

**Comment by ucirello** [comment]
I am not sure I understand what you are reporting. Could you please provide me with a reproduction case?

**Comment by davidjumani** [comment]
From what I can see, we first do a getItem() to retrieve the details of the existing lock, followed by a putItem() to store the current lock. However, during the time between the getItem() and the putItem(), if the locked row's additional attributes have been changed, they get overwritten by the stale attributes fetched in the prior getItem() during the getLockFromDynamoDB() call. To solve this, wouldn't it be better to use an updateItem() instead of the putItem() called while storing the lock with just the attributes to be changed?
Can reproduce this while running multiple concurrent lock requests to an item, with each request modifying the locked item's attributes prior to releasing the lock.

**Comment by ucirello** [comment]
@davidjumani I think I understand what you are saying. 

I still need a piece of code that I can use to reproduce the problem - otherwise, I am going to be guessing if I actually found the problem or not.

**Comment by ucirello** [comment]
@davidjumani could you please share the piece of code that reproduces this behavior? I'd rather use a piece of code you give to reproduce the problem instead of guessing what the problem actually is.

**Comment by ucirello** [comment]
Just another note, I am inclined to say that maybe this is working as intended. The additional attributes of a lock must not be overwritten by mutually exclusive acquisition requests.

**Comment by davidjumani** [comment]
`
package main

import (
	"time"
	"net/http"
	"strconv"
	"reflect"

	"github.com/go-chi/chi"

	log "github.com/Sirupsen/logrus"

	"cirello.io/dynamolock"

	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/dynamodb"
	"github.com/aws/aws-sdk-go/service/dynamodb/expression"

)

var tableName string
var partitionKey string
var svc *dynamodb.DynamoDB
var lockClient *dynamolock.Client

type attrib struct {
	i int64 `json:"i"`
}


func createLockClient() (*dynamolock.Client) {
	c, err := dynamolock.New(svc,
		tableName,
		dynamolock.WithLeaseDuration(3*time.Second),
		dynamolock.WithHeartbeatPeriod(1*time.Second),
		dynamolock.WithPartitionKeyName(partitionKey),
		dynamolock.WithLogger(log.New()),
	)
	if err != nil {
		log.Fatal(err)
	}

	log.Println("ensuring table exists")
	c.CreateTable(tableName,
		dynamolock.WithCustomPartitionKeyName(partitionKey),
		dynamolock.WithProvisionedThroughput(
			&dynamodb.ProvisionedThroughput{
				ReadCapacityUnits:  aws.Int64(5),
				WriteCapacityUnits: aws.Int64(5),
			}),
	)
	log.Println("Created table")
	return c
}

func createAwsClient() (*dynamodb.DynamoDB) {
	config := aws.NewConfig().WithRegion("us-west-2").WithEndpoint("http://localhost:8000")
	sess := session.Must(session.NewSession(config))
	svc := dynamodb.New(sess)
	return svc
}

func closeLock(lockedItem *dynamolock.Lock) {
	success, err := lockClient.ReleaseLock(lockedItem)
	if !success {
		log.Println(err)
		log.Fatal("lost lock before release")
	}
	if err != nil {
		log.Fatal("error releasing lock:", err)
	}
}

func getLock(key string) (*dynamolock.Lock) {
	var orgRecord *dynamolock.Lock
	var err error
	for {
		orgRecord, err = lockClient.AcquireLock(key,
			)
		if err == nil  {
			break
		}
	}
	return orgRecord
}

func updateOrgRecord(key string, i int64) {
	log.Info("Updating ", key)
	update := expression.Set(
		expression.Name("i"),
		expression.Value(i),
		)
	expr, err := expression.NewBuilder().WithUpdate(update).Build()
	if err != nil {
		log.Fatal(err.Error())
	}
	updateRecord(key, &expr)
}

func updateRecord(key string, expr *expression.Expression) {
	input := &dynamodb.UpdateItemInput{
		ExpressionAttributeNames:  expr.Names(),
		ExpressionAttributeValues: expr.Values(),
		Key: map[string]*dynamodb.AttributeValue {
			partitionKey: {
				S: aws.String(key),
			},
		},
		ReturnValues:     aws.String("ALL_NEW"),
		TableName:        aws.String(tableName),
		UpdateExpression: expr.Update(),
	}
	log.Info(input)
	_, err := svc.UpdateItem(input)
	if err != nil {
		log.Fatal(err.Error())
	}
}

func test(w http.ResponseWriter, r *http.Request) {
	key := "this"
	orgRecord := getLock(key)
	log.Info(orgRecord.AdditionalAttributes())

	var i int64
	attrib :=  orgRecord.AdditionalAttributes()
	if len(orgRecord.AdditionalAttributes()) == 0 {
		i = 0
	} else {
		i, _ = strconv.ParseInt(*attrib["i"].N, 10, 64)
	}
	i = i + 1
	log.Info("i ", i)
	log.Info(reflect.TypeOf(i))
	updateOrgRecord(key, i)
	closeLock(orgRecord)
	w.Write([]byte(strconv.FormatInt(i, 10)))
}

func main() {
	tableName = "test"
	partitionKey = "key"

	svc = createAwsClient()
	lockClient = createLockClient()

	r := chi.NewRouter()
	r.Get("/", test)

	http.ListenAndServe(":8080", r)
}
`

**Comment by davidjumani** [comment]
Updating the records as there's no save modified attributes on close.
Bombard the api with around 30 concurrent requests via j meter.
The additional attribute `i` should finally be 30, but instead is much lower
Possibly due to executing updateRecord()  in test() occurring between the getItem() and putItem() while trying to acquire the lock by another simultaneous request.
[test.txt](https://github.com/cirello-io/dynamolock/files/2934858/test.txt)

**Comment by ucirello** [comment]
Thanks for the code snippet.

It is working as intended. The dynamodb entity holding locks shouldn't be modified out of the library.

The right thing to do here is to use the dynamolock to hold a lock while operating on something else.

**Comment by davidjumani** [comment]
However, there is no option to modify the attributes and save them while releasing the lock. Perhaps that could be an additional feature?

**Comment by ucirello** [comment]
@davidjumani that would certainly be an enhancement, although I fail to see if this would be useful to the majority of the users of dynamolock. 

Would you like to give it a try coding this and open a PR?

**Comment by davidjumani** [comment]
Sure. I'm working on it!
