### ISSUE TITLE
Any way to wait for a lease to timeout other than an AcquireLock call?

### ISSUE THREAD

**Issue by taylor-sutton** [cirello-io/dynamolock#84]
Use case: I have short-lived processes where I can't really wait for my whole lease duration all at once and hope that I get the lock, even with, say, 1-minute leases. I'd rather check if key is locked and if it is, spin down the process/allow it to move on and then check again after lease duration if the rvn has changed. Basically what AcquireLock already does, but manually so I can do other stuff in between. 

It seems that, since the API doesn't expose the record-version-number and lease duration, there is no way to do an AcquireLock with FailIfLocked and then manually manage checking to see if the lock has the same version after lease duration has passed. So that, if I want to wait for a lease to expire, the only choice is to block for lease duration in an AcquireLock call. Is that all correct? If so, maybe there could be a way to Acquire plus FailIfLocked plus retrieve some data that could be used to actually acquire the lock once the lease duration has passed.

Again, I might be able to get a PR, but would like some guidance before coding.

**Comment by ucirello** [comment]
@taylor-sutton -- thanks for reaching out.

If I understand correctly what you are asking, what you want is the manual heartbeat support. Create a client with heartbeat disabled (https://godoc.org/cirello.io/dynamolock#DisableHeartbeat), and then manually call the `client.SendHeartbeat` (https://godoc.org/cirello.io/dynamolock#Client.SendHeartbeat) to prove that you still own the lock. This second command is going to fail if you lose the lock, and then you are going to be able to bail out if it does.

**Comment by ucirello** [comment]
Hey @taylor-sutton - I am going to close this issue. Please reopen it if you need more support. Thanks
